### ISSUE TITLE
Everything looks very vague on Windows Phone 8.1 for win8.1 universal app.

### ISSUE THREAD

**Issue by JiekeZhu** [Microsoft/cocos2d-x#156]
Hi there,
I'm going to release my game soon.  

However, I find everything on the screen looks vague, not as clear as the original images. It looks good on WP8 with old angle (with memory problem). 

And there are also blank edges on top and right of the screen.
This is a screenshot on one of my windows phone 8.1 devices.
![wp_ss_20150604_0010 1](https://cloud.githubusercontent.com/assets/11001280/8003343/36c43b4c-0ba9-11e5-8fa6-622d8732cfd4.png)

This is the original image.
![splash](https://cloud.githubusercontent.com/assets/11001280/8003378/9ff6b306-0ba9-11e5-8be9-388fa844ab68.png)

I have tested with cocos2d-x-3.4, cocos2d-x-3.5, cocos2d-x-3.6-uap, the same result!!!

Steps
1. Create a simple game with cocos new MyGame -p com.my_company.mygame -l cpp -d projectdir
2. Add a sprite on the layer.

bool HelloWorld::init()
{
    //////////////////////////////
    // 1. super init first
    if ( !Layer::init() )
    {
        return false;
    }
    
	// ....
	
	Sprite* bgSprite = Sprite::create("splash.png");
	bgSprite->setAnchorPoint(Point::ZERO);
	this->addChild(bgSprite);

    return true;
}

Please help with this problem. I have no idea how to configure cocos2d-x or angle to make it work correctly.

Thanks in advance.

**Comment by kidproquo** [comment]
I have the same issue! Users have complained that my game images look blurry.

**Comment by stammen** [comment]
The current version of Angle for Windows Phone 8.1 uses the logical DPI of the screen and not the full resolution. This is why images are fuzzy at HD screen resolutions (because 2x scaling is happening).

 We hope to add support for HD screens in cocos2d-x v3.8. You will be able to dial in the resolution versus frame rate for your game on HD devices. Some HD Windows Phones are not capable of 60 FPS at full screen resolution for more complex games.

**Comment by JiekeZhu** [comment]
Thanks for the quick response. Appreciated.

Could you please give me some temporary solution for this ?
Can I add some code in cocos2d-x project to configure it ?
Or I should modify the Angle code to make sure it use the right DPI for the resolution ? Forgive me about not clearly understanding the work system in Angle.

Currently this problem appears on the windows phone simulator and all my devices. Wait for the coming version and release my game with this problem make me feel frustrated.

**Comment by stammen** [comment]
Here is some code you can use to fix the resolution issue. This is based on v3.10 or higher.

The problem is that the Windows Phone version of cocos2d-x is not rendering at the full screen resolution of the device. 

Please try the following:

1) In Cocos2dEngine\OpenGLESPage.xaml.cpp add the following around line 154

void OpenGLESPage::CreateRenderSurface()
{
if (mOpenGLES && mRenderSurface == EGL_NO_SURFACE)
{
// The app can configure the the SwapChainPanel which may boost performance.
// By default, this template uses the default configuration.
//mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, nullptr, nullptr);

    Windows::Graphics::Display::DisplayInformation^ info = Windows::Graphics::Display::DisplayInformation::GetForCurrentView();
    auto screenResolutionScale = info->LogicalDpi / 96.0f;

    // You can configure the SwapChainPanel to render at a lower resolution and be scaled up to
    // the swapchain panel size. This scaling is often free on mobile hardware.
    //
    // One way to configure the SwapChainPanel is to specify precisely which resolution it should render at.
    // Size customRenderSurfaceSize = Size(800, 600);
    // mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, &customRenderSurfaceSize, nullptr);
    //
    // Another way is to tell the SwapChainPanel to render at a certain scale factor compared to its size.
    // e.g. if the SwapChainPanel is 1920x1280 then setting a factor of 0.5f will make the app render at 960x640
    mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, nullptr, &screenResolutionScale);
    // 
}
}

2) In libcocos2d/platform/winrt/cocos2dCCGLViewImpl-winrt.h add the following around line 190

float m_screenResolutionScale;
3) In lib/platform/winrt/cocos2dCCGLViewImpl-winrt.cpp add the following around line 94

, m_screenResolutionScale(1.0f)
4) In libcocos2d/platform/winrt/cocos2dCCGLViewImpl-winrt.cpp add the following around line 131

m_screenResolutionScale = m_dpi / 96.0f;
4) In libcocos2d/platform/winrt/cocos2dCCGLViewImpl-winrt.cpp change the following around line 557

float x = p.X * m_screenResolutionScale;
float y = p.Y * m_screenResolutionScale;
returnValue = Vec2(x, y);

You may see a drop in FPS since the ANGLE is now pushing a lot more pixels to the screen. Please let me know if this improves the quality of your textures and we can work together to get these changes into cocos2d-x.
